name: Dependency Management

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday
  workflow_dispatch:  # Allow manual trigger

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Check for updates
      uses: renovatebot/github-action@v39.1.1
      with:
        configurationFile: renovate.json
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: npm run install-all

    - name: Run npm audit
      run: |
        npm audit
        cd client && npm audit
        cd ../server && npm audit

    - name: Create Issue on Security Vulnerability
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Security Vulnerabilities Detected',
            body: 'npm audit has detected security vulnerabilities. Please review the workflow logs.'
          })